# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy



builds:
  - env:
      - CGO_ENABLED=1
    goos:
      # - linux
      # - windows
      - darwin
    goarch:
      # - amd64
      # - 386
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: false
  github:
    owner: srv332003
    name: go_music

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

nfpms:
  - package_name: go_music
    homepage: https://github.com/SRV332003/go_music/
    maintainer: Sourav <srvgarg332003@gmail.com>
    description: |-
            A perfect music companion for you and your Terminal.🔥🔥
    formats:
      - rpm
      - deb

sboms:
  - artifacts: archive
    

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  
brews:
    - name: go_music
      commit_author:
        name: srv332003
        email: srvgarg332003@gmail.com
      homepage: https://github.com/srv332003/go_music
      description: A perfect music companion for you and your Terminal.🔥🔥