# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMusic < Formula
  desc "A perfect music companion for you and your Terminal.🔥🔥"
  homepage "https://github.com/srv332003/go_music"
  version "1.0.5"
  license "MIT"

  depends_on "ffmpeg" if OS.mac?
  depends_on :macos

  on_arm do
    url "https://github.com/SRV332003/go_music/releases/download/v1.0.5/go_music_Darwin_arm64.tar.gz"
    sha256 "25827716a253493afc8194f61402937c9476eeae9e8299f591822f2bfd97e74b"

    def install
      bin.install "go_music"
    end
  end
end
